services:
  - type: web
    name: qingjin-market
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production